name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build project
        run: npm run build

      - name: Add CNAME for deployment
        run: |
          touch out/CNAME
          echo "roses.media" >> out/CNAME

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./out

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
